// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2VvzgKSAZKeGFRxq83fuijrtGSwSO9co',
    appId: '1:457191917761:web:848a6d92f9fa932cc72c40',
    messagingSenderId: '457191917761',
    projectId: 'fooddeliveryapp-67389',
    authDomain: 'fooddeliveryapp-67389.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-67389.appspot.com',
    measurementId: 'G-4HSMM95DFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNK2-obArZU7qst1LXOrZYyzkpdk8GeyQ',
    appId: '1:457191917761:android:aa87bd643f07c34dc72c40',
    messagingSenderId: '457191917761',
    projectId: 'fooddeliveryapp-67389',
    storageBucket: 'fooddeliveryapp-67389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCalJLp1elZuK0YT6WD_4ae1PmQLRjdzco',
    appId: '1:457191917761:ios:078604a6bebc7dfec72c40',
    messagingSenderId: '457191917761',
    projectId: 'fooddeliveryapp-67389',
    storageBucket: 'fooddeliveryapp-67389.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCalJLp1elZuK0YT6WD_4ae1PmQLRjdzco',
    appId: '1:457191917761:ios:078604a6bebc7dfec72c40',
    messagingSenderId: '457191917761',
    projectId: 'fooddeliveryapp-67389',
    storageBucket: 'fooddeliveryapp-67389.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2VvzgKSAZKeGFRxq83fuijrtGSwSO9co',
    appId: '1:457191917761:web:c763a39f4c5772c8c72c40',
    messagingSenderId: '457191917761',
    projectId: 'fooddeliveryapp-67389',
    authDomain: 'fooddeliveryapp-67389.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-67389.appspot.com',
    measurementId: 'G-5HG2Z69968',
  );
}
